name: Zigtask API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'zigtask-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'zigtask-api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: zigtask-api
      run: npm install
    
    - name: Run tests
      working-directory: zigtask-api
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      run: npm test
    
    - name: Lint
      working-directory: zigtask-api
      run: npm run lint
